apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ethereum-client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: ethereum-client
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
