apiVersion: v1
kind: Secret
metadata:
  name: ethereum-secrets
type: Opaque
data:
  rpc-auth: c3VwZXJzZWNyZXQ=  
  db-username: ZGJ1c2Vy  
  db-password: cGFzc3dvcmQ=  
  api-token: YXBpLXRva2VuLXNlY3JldA==  
