FROM jenkins/jenkins:lts

# Switch to root user to install Node.js
USER root

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

# Switch back to the Jenkins user
USER jenkins

# Install necessary Jenkins plugins
RUN jenkins-plugin-cli --plugins workflow-aggregator docker-workflow blueocean

# Expose the default Jenkins port
EXPOSE 8080
