pipeline {
    agent {
        dockerfile {
            filename 'DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/Dockerfile'
            dir 'DEVOPS_BLCKCHAIN_ADMIN_CRN_82150'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [], 
                    userRemoteConfigs: [[
                        url: 'https://github.com/hafelago/Scalable-Blockchain-Applications.git',
                        credentialsId: 'da17bf46-97c3-4463-a5ab-45cabc0bbc53' // Use your actual credentials ID
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                script {
                    // Install project dependencies
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Run Jest tests
                    sh 'npm test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
    post {
        always {
            junit 'DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/reports/test-results.xml' // Ensure this path matches your Jest configuration
        }
    }
}
