pipeline {
    agent {
        docker {
            image 'hafelago/my-jenkins-with-nodejs:latest'
            label 'my-nodejs-agent' // Optional: specify a label if you want to restrict to specific agents
            args '-v /var/run/docker.sock:/var/run/docker.sock' // Optional: add any necessary Docker run arguments
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [], 
                    userRemoteConfigs: [[
                        url: 'https://github.com/hafelago/Scalable-Blockchain-Applications.git',
                        credentialsId: 'da17bf46-97c3-4463-a5ab-45cabc0bbc53'
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                script {
                    // Install project dependencies
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Run Jest tests
                    sh 'npm test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
    post {
        always {
            script {
                junit 'DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/Calculator/reports/test-results.xml' // Ensure this path matches your Jest configuration
            }
        }
    }
}
