name: Node.js CI and Jest Tests after CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["CI-CD"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm test

  test_after_ci_cd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npx yarn
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Run Tests
        run: npx yarn test
