name: Node.js CI, Jest Tests with Linting, Import Secrets, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["CI-CD"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm test

  test_after_ci_cd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npx yarn
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Run Tests
        run: npx yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install  
      - name: Run Lint Checks
        run: npm run style  
      - name: Set up API key
        run: echo "API_KEY=${{ secrets.TEST }}" >> $GITHUB_ENV

  import_and_publish:
    runs-on: ubuntu-latest
    needs: [build, lint]  # Asegúrate de que los pasos anteriores se hayan completado antes de ejecutar este
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        id: secrets
        with:
          url: https://vault.example.com/ 
          role: content
          method: jwt
          secrets: |
            kv/data/content/codio-ed-dev client_id;
            kv/data/content/codio-ed-dev secret_id;
      - name: Publish
        uses: codio/codio-assignment-publish-action@master
        with:
          client-id: ${{ steps.secrets.outputs.client_id }}
          secret-id: ${{ steps.secrets.outputs.secret_id }}
          course-name: <Devops>
          assignment-name: <Lab1>
          dir: ./
          changelog: ${{ github.event.head_commit.message }}
