name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Change to Calculator directory
        run: cd Calculator

      - name: Install dependencies
        run: npm install
        working-directory: Calculator

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: Calculator/dist

          # Fetch the secret API key
      - name: Set up API key
        run: echo "API_KEY=${{ secrets.TEST_SECRET }}" >> $GITHUB_ENV

      - name: Use API key
        run: echo "The API key is $API_KEY"

      - name: Install dependencies
        run: yarn
      - uses: actions/download-artifact@v2
        with:
          name: assets
          path: Calculator/dist
      - name: Run Lint Checks
        run: yarn eslint
        working-directory: Calculator
