name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents for debugging
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: ./DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/Calculator

      - name: Run Jest tests
        run: npm test
        working-directory: ./DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/Calculator

      - name: Archive dist folder
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: DEVOPS_BLCKCHAIN_ADMIN_CRN_82150/Calculator/dist

      - name: Fetch the secret API key
        run: echo "API_KEY=${{ secrets.TEST_SECRET }}" >> $GITHUB_ENV

      - name: Use API key
        run: echo "The API key is $API_KEY"
